[workspace]
members = ["crates/batter", "crates/batter-axum", "crates/batter-test-support", "examples/postgres-lifecycle"]
default-members = ["crates/batter", "crates/batter-axum", "crates/batter-test-support"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.lints.clippy]
cognitive_complexity = "warn"
too_many_lines = "warn"

[workspace.dependencies]
batter = { path = "crates/batter" }
batter-test-support = { path = "crates/batter-test-support" }
pin-project-lite = "0.2.17"
tokio = { version = "1.53.1", default-features = false }
tokio-util = { version = "0.7.19", default-features = false }
tracing = "0.1.44"
tracing-core = "0.1.36"
thiserror = "2.0.20"
axum = "0.8.9"
serde = "1.0.229"
sqlx = { version = "0.9.0", default-features = false }
tracing-subscriber = "0.3.23"
tower = "0.5.3"
