-- Frozen expected grants for RunledgerOperation::DirectJobExecution.
GRANT USAGE ON SCHEMA "jobs" TO "jobs_service";
GRANT DELETE ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT DELETE ON TABLE "jobs"."job_execution_resource_claims" TO "jobs_service";
GRANT DELETE ON TABLE "jobs"."workflow_active_claims" TO "jobs_service";
GRANT SELECT ("attempt"), INSERT ("attempt") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT SELECT ("claim_origin"), INSERT ("claim_origin") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT UPDATE ("effective_next_run_at") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT UPDATE ("error_code") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT UPDATE ("error_message") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT SELECT ("execution_started_persisted_at"), INSERT ("execution_started_persisted_at"), UPDATE ("execution_started_persisted_at") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT UPDATE ("finished_at") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT SELECT ("job_id"), INSERT ("job_id") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT INSERT ("leased_at") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT UPDATE ("outcome") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT UPDATE ("requested_retry_not_before") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT UPDATE ("retry_delay_ms") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT UPDATE ("retry_timing_source") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT SELECT ("run_number"), INSERT ("run_number") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT INSERT ("started_at") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT INSERT ("worker_id") ON TABLE "jobs"."job_attempts" TO "jobs_service";
GRANT SELECT ("attempt"), INSERT ("attempt"), UPDATE ("attempt") ON TABLE "jobs"."job_dead_letters" TO "jobs_service";
GRANT SELECT ("checkpoint_snapshot"), INSERT ("checkpoint_snapshot"), UPDATE ("checkpoint_snapshot") ON TABLE "jobs"."job_dead_letters" TO "jobs_service";
GRANT SELECT ("error_code"), INSERT ("error_code"), UPDATE ("error_code") ON TABLE "jobs"."job_dead_letters" TO "jobs_service";
GRANT SELECT ("error_message"), INSERT ("error_message"), UPDATE ("error_message") ON TABLE "jobs"."job_dead_letters" TO "jobs_service";
GRANT SELECT ("failed_at"), INSERT ("failed_at"), UPDATE ("failed_at") ON TABLE "jobs"."job_dead_letters" TO "jobs_service";
GRANT SELECT ("job_id"), INSERT ("job_id") ON TABLE "jobs"."job_dead_letters" TO "jobs_service";
GRANT INSERT ("job_type") ON TABLE "jobs"."job_dead_letters" TO "jobs_service";
GRANT INSERT ("organization_id") ON TABLE "jobs"."job_dead_letters" TO "jobs_service";
GRANT SELECT ("payload_snapshot"), INSERT ("payload_snapshot"), UPDATE ("payload_snapshot") ON TABLE "jobs"."job_dead_letters" TO "jobs_service";
GRANT SELECT ("run_number"), INSERT ("run_number"), UPDATE ("run_number") ON TABLE "jobs"."job_dead_letters" TO "jobs_service";
GRANT SELECT ("attempt"), INSERT ("attempt") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT SELECT ("event_type"), INSERT ("event_type") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT SELECT ("id") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT SELECT ("job_id"), INSERT ("job_id") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT SELECT ("occurred_at") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT INSERT ("payload") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT INSERT ("progress_done") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT INSERT ("progress_total") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT SELECT ("run_number"), INSERT ("run_number") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT SELECT ("stage"), INSERT ("stage") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT SELECT ("attempt"), INSERT ("attempt") ON TABLE "jobs"."job_execution_resource_claims" TO "jobs_service";
GRANT SELECT ("job_id"), INSERT ("job_id") ON TABLE "jobs"."job_execution_resource_claims" TO "jobs_service";
GRANT SELECT ("lease_expires_at"), INSERT ("lease_expires_at"), UPDATE ("lease_expires_at") ON TABLE "jobs"."job_execution_resource_claims" TO "jobs_service";
GRANT SELECT ("release_after") ON TABLE "jobs"."job_execution_resource_claims" TO "jobs_service";
GRANT SELECT ("resource_key"), INSERT ("resource_key") ON TABLE "jobs"."job_execution_resource_claims" TO "jobs_service";
GRANT SELECT ("run_number"), INSERT ("run_number") ON TABLE "jobs"."job_execution_resource_claims" TO "jobs_service";
GRANT SELECT ("worker_id"), INSERT ("worker_id") ON TABLE "jobs"."job_execution_resource_claims" TO "jobs_service";
GRANT SELECT ("attempt"), UPDATE ("attempt") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("checkpoint"), UPDATE ("checkpoint") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("created_at") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("execution_resource_key") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("finished_at"), UPDATE ("finished_at") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("id") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("idempotency_key") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("job_type") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("last_error_code"), UPDATE ("last_error_code") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("last_error_message"), UPDATE ("last_error_message") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("last_heartbeat_at"), UPDATE ("last_heartbeat_at") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("lease_expires_at"), UPDATE ("lease_expires_at") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("max_attempts") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("next_run_at"), UPDATE ("next_run_at") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("organization_id") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("output"), UPDATE ("output") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("payload") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("priority") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("progress_done"), UPDATE ("progress_done") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("progress_pct") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("progress_total"), UPDATE ("progress_total") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("run_number"), UPDATE ("run_number") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("stage"), UPDATE ("stage") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("started_at"), UPDATE ("started_at") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("status"), UPDATE ("status") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("status_reason"), UPDATE ("status_reason") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("timeout_seconds") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("updated_at"), UPDATE ("updated_at") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("worker_id"), UPDATE ("worker_id") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("active_key") ON TABLE "jobs"."workflow_active_claims" TO "jobs_service";
GRANT SELECT ("release_pending") ON TABLE "jobs"."workflow_active_claims" TO "jobs_service";
GRANT SELECT ("scope") ON TABLE "jobs"."workflow_active_claims" TO "jobs_service";
GRANT SELECT ("updated_at"), UPDATE ("updated_at") ON TABLE "jobs"."workflow_active_claims" TO "jobs_service";
GRANT SELECT ("workflow_run_id") ON TABLE "jobs"."workflow_active_claims" TO "jobs_service";
GRANT SELECT ("allow_handler_continuation") ON TABLE "jobs"."workflow_steps" TO "jobs_service";
GRANT SELECT ("execution_kind") ON TABLE "jobs"."workflow_steps" TO "jobs_service";
GRANT UPDATE ("finished_at") ON TABLE "jobs"."workflow_steps" TO "jobs_service";
GRANT SELECT ("id") ON TABLE "jobs"."workflow_steps" TO "jobs_service";
GRANT SELECT ("job_id") ON TABLE "jobs"."workflow_steps" TO "jobs_service";
GRANT UPDATE ("last_error_code") ON TABLE "jobs"."workflow_steps" TO "jobs_service";
GRANT UPDATE ("last_error_message") ON TABLE "jobs"."workflow_steps" TO "jobs_service";
GRANT UPDATE ("output") ON TABLE "jobs"."workflow_steps" TO "jobs_service";
GRANT SELECT ("started_at"), UPDATE ("started_at") ON TABLE "jobs"."workflow_steps" TO "jobs_service";
GRANT SELECT ("status"), UPDATE ("status") ON TABLE "jobs"."workflow_steps" TO "jobs_service";
GRANT UPDATE ("status_reason") ON TABLE "jobs"."workflow_steps" TO "jobs_service";
GRANT UPDATE ("updated_at") ON TABLE "jobs"."workflow_steps" TO "jobs_service";
GRANT SELECT ("workflow_run_id") ON TABLE "jobs"."workflow_steps" TO "jobs_service";
