-- Frozen expected grants for RunledgerOperation::IntentPromotion.
GRANT USAGE ON SCHEMA "jobs" TO "jobs_service";
GRANT SELECT ("default_priority") ON TABLE "jobs"."job_definitions" TO "jobs_service";
GRANT SELECT ("default_timeout_seconds") ON TABLE "jobs"."job_definitions" TO "jobs_service";
GRANT SELECT ("is_enabled") ON TABLE "jobs"."job_definitions" TO "jobs_service";
GRANT SELECT ("job_type") ON TABLE "jobs"."job_definitions" TO "jobs_service";
GRANT SELECT ("max_attempts") ON TABLE "jobs"."job_definitions" TO "jobs_service";
GRANT UPDATE ("updated_at") ON TABLE "jobs"."job_definitions" TO "jobs_service";
GRANT UPDATE ("conflicted_at") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("created_at") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("enqueue_request") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("enqueue_request_version") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("execution_resource_key") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("id") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("idempotency_key") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("job_type") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT UPDATE ("last_attempted_at") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT UPDATE ("last_error_code") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT UPDATE ("last_error_message") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("max_attempts") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("next_promotion_at"), UPDATE ("next_promotion_at") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("next_run_at") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("organization_id") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("payload") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("priority") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT UPDATE ("promoted_at") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT UPDATE ("promoted_job_id") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("promotion_attempts"), UPDATE ("promotion_attempts") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("stage") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("status"), UPDATE ("status") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT SELECT ("timeout_seconds") ON TABLE "jobs"."job_enqueue_intents" TO "jobs_service";
GRANT INSERT ("event_type") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT INSERT ("job_id") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT INSERT ("payload") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT INSERT ("run_number") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT INSERT ("stage") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT SELECT ("enqueue_request"), INSERT ("enqueue_request") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("execution_resource_key") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("id"), UPDATE ("id") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("idempotency_key"), INSERT ("idempotency_key") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("job_type"), INSERT ("job_type") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("max_attempts") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("next_run_at") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("organization_id"), INSERT ("organization_id") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("payload") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("priority") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("run_number") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("stage") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("status") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("timeout_seconds") ON TABLE "jobs"."job_queue" TO "jobs_service";
