-- Frozen expected grants for RunledgerOperation::ScheduledDispatch.
GRANT USAGE ON SCHEMA "jobs" TO "jobs_service";
GRANT MAINTAIN ON TABLE "jobs"."job_schedules" TO "jobs_service";
GRANT SELECT ("default_priority") ON TABLE "jobs"."job_definitions" TO "jobs_service";
GRANT SELECT ("default_timeout_seconds") ON TABLE "jobs"."job_definitions" TO "jobs_service";
GRANT SELECT ("is_enabled") ON TABLE "jobs"."job_definitions" TO "jobs_service";
GRANT SELECT ("job_type") ON TABLE "jobs"."job_definitions" TO "jobs_service";
GRANT SELECT ("max_attempts") ON TABLE "jobs"."job_definitions" TO "jobs_service";
GRANT UPDATE ("updated_at") ON TABLE "jobs"."job_definitions" TO "jobs_service";
GRANT INSERT ("event_type") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT INSERT ("job_id") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT INSERT ("payload") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT INSERT ("run_number") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT INSERT ("stage") ON TABLE "jobs"."job_events" TO "jobs_service";
GRANT INSERT ("enqueue_request") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("execution_resource_key") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("id") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("idempotency_key") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("job_type") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("max_attempts") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("next_run_at") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("organization_id") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("payload") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("priority") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("run_number") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("stage") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("status") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT INSERT ("timeout_seconds") ON TABLE "jobs"."job_queue" TO "jobs_service";
GRANT SELECT ("cron_expr") ON TABLE "jobs"."job_schedules" TO "jobs_service";
GRANT SELECT ("id") ON TABLE "jobs"."job_schedules" TO "jobs_service";
GRANT SELECT ("is_active") ON TABLE "jobs"."job_schedules" TO "jobs_service";
GRANT SELECT ("job_type") ON TABLE "jobs"."job_schedules" TO "jobs_service";
GRANT UPDATE ("last_fired_at") ON TABLE "jobs"."job_schedules" TO "jobs_service";
GRANT SELECT ("max_jitter_seconds") ON TABLE "jobs"."job_schedules" TO "jobs_service";
GRANT SELECT ("name") ON TABLE "jobs"."job_schedules" TO "jobs_service";
GRANT SELECT ("next_fire_at"), UPDATE ("next_fire_at") ON TABLE "jobs"."job_schedules" TO "jobs_service";
GRANT SELECT ("organization_id") ON TABLE "jobs"."job_schedules" TO "jobs_service";
GRANT SELECT ("payload_template") ON TABLE "jobs"."job_schedules" TO "jobs_service";
GRANT UPDATE ("updated_at") ON TABLE "jobs"."job_schedules" TO "jobs_service";
